name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Test Android compilation
      run: ./gradlew :auth_shared:compileDebugKotlinAndroid
    
    - name: Test iOS compilation
      run: ./gradlew :auth_shared:compileKotlinIosArm64
    
    - name: Test metadata compilation
      run: ./gradlew :auth_shared:compileKotlinMetadata
    
    - name: Test JS compilation
      run: ./gradlew :auth_shared:compileKotlinJs
    
    - name: Test WASM compilation
      run: ./gradlew :auth_shared:compileKotlinWasmJs
    
    - name: Run unit tests
      run: ./gradlew :auth_shared:testDebugUnitTest
    
    - name: Build all targets
      run: ./gradlew :auth_shared:build
